version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_TCP_PORT: 3308
    ports:
    - 3308:3308
    expose:
      - 3308
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      mysql:
        condition: service_healthy
    build: ./
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=mydb
      - DB_PORT=3308
    stdin_open: true
    tty: true

volumes: 
  db: